/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HWK9;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author steve
 */
public class MI3A_26_HWK9_03 extends javax.swing.JFrame implements ListSelectionListener{

    /**
     * Creates new form MI3A_26_HWK9_03
     */
    DefaultListModel dlm1 = new DefaultListModel();
    DefaultListModel dlm2 = new DefaultListModel();
    String merPath = "D:/Data/HWK9/merchandise.txt";
    boolean insert = true;
    
    public MI3A_26_HWK9_03() throws IOException{
        initComponents();
        merchandise.setModel(dlm1);
        userlist.setModel(dlm2);
        loadMerchandise(merPath, dlm1);
        this.merchandise.addListSelectionListener(this);
        this.userlist.addListSelectionListener(this);
    }
    
    public void loadMerchandise(String path, DefaultListModel dlm) throws IOException{
        try(BufferedReader br = new BufferedReader(new FileReader(path))){
            String line, total = "";
            while((line=br.readLine()) != null){
                total += line+"\n";
            }
            String[] item = total.split("\n");

            for(String s : item){
                dlm.addElement(s);
            }
        }
    }

    @Override
    public void valueChanged(ListSelectionEvent e) {
        
        if(e.getSource() == merchandise){
            if(ICanInsert()){
                dlm2.removeAllElements();
                addToUserlist();
            }
        }
    }

    public void addToUserlist(){
        int[] indices1 = merchandise.getSelectedIndices();  // 取得所有被選取項目的Index
        for(int i : indices1){
            dlm2.addElement(dlm1.getElementAt(i));
        }
    }

    public boolean ICanInsert(){
        if(insert == true)
            insert = false;
            
        else if(insert == false)
            insert = true;
        
        return insert;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        merchandise = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        userlist = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        merchandise.setFont(new java.awt.Font("Klee One", 1, 18)); // NOI18N
        merchandise.setToolTipText("");
        merchandise.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(merchandise);

        getContentPane().add(jScrollPane1);

        userlist.setFont(new java.awt.Font("Klee One", 1, 18)); // NOI18N
        userlist.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(userlist);

        getContentPane().add(jScrollPane2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MI3A_26_HWK9_03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MI3A_26_HWK9_03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MI3A_26_HWK9_03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MI3A_26_HWK9_03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MI3A_26_HWK9_03().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(MI3A_26_HWK9_03.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> merchandise;
    private javax.swing.JList<String> userlist;
    // End of variables declaration//GEN-END:variables

    
}
