/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MI3A_26_408630852;

import java.awt.BorderLayout;
import java.awt.Container;
import javax.swing.ImageIcon;

/**
 *
 * @author steve
 */
public class MI3A_26_02 extends javax.swing.JFrame {

    /**
     * Creates new form MI3A_26_02
     */
    ImageIcon[] imgs = new ImageIcon[15];
    boolean playControl = false;
    int nowImage = 0;
    
    public MI3A_26_02() {
        initComponents();
        setSize(200, 250);
        Container cp = this.getContentPane();
        cp.setLayout(new BorderLayout());
        
        cp.add(load, BorderLayout.NORTH);
        cp.add(imgArea, BorderLayout.CENTER);
        cp.add(btnArea, BorderLayout.SOUTH);
        
        fillImage();
    }
    
    public void fillImage(){
        for(int i = 0; i < imgs.length; i++){
            if(i < 10){
                imgs[i] = new ImageIcon("C:\\Users\\steve\\OneDrive\\文件\\NetBeansProjects\\FinalTest\\src\\MI3A\\duke_gif/duke0" + i + ".gif");
            }
            else if(i >= 10){
                imgs[i] = new ImageIcon("C:\\Users\\steve\\OneDrive\\文件\\NetBeansProjects\\FinalTest\\src\\MI3A\\duke_gif/duke" + i + ".gif");
        }
            }
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        load = new javax.swing.JButton();
        imgArea = new javax.swing.JPanel();
        leftImg = new javax.swing.JLabel();
        rightImg = new javax.swing.JLabel();
        btnArea = new javax.swing.JPanel();
        right = new javax.swing.JButton();
        play = new javax.swing.JButton();
        left = new javax.swing.JButton();
        stop = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        load.setText("Load Image");
        load.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadActionPerformed(evt);
            }
        });

        imgArea.setLayout(new java.awt.GridLayout(1, 2));
        imgArea.add(leftImg);
        imgArea.add(rightImg);

        btnArea.setLayout(new java.awt.GridLayout(2, 2));

        right.setText(">");
        right.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightActionPerformed(evt);
            }
        });
        btnArea.add(right);

        play.setText("Play");
        play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playActionPerformed(evt);
            }
        });
        btnArea.add(play);

        left.setText("<");
        left.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftActionPerformed(evt);
            }
        });
        btnArea.add(left);

        stop.setText("Stop");
        stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopActionPerformed(evt);
            }
        });
        btnArea.add(stop);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(load, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(imgArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(159, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(load)
                .addGap(45, 45, 45)
                .addComponent(imgArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                .addComponent(btnArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadActionPerformed
        // TODO add your handling code here:
        leftImg.setIcon(imgs[0]);
        load.setText("Load Image(duke00.gif)");
    }//GEN-LAST:event_loadActionPerformed

    private void playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playActionPerformed
        // TODO add your handling code here:
        if(playControl == false){
            playControl = true;
            new Thread(()->{
                while(playControl){
                    if(++nowImage > imgs.length-1){
                        nowImage = 0;
                    }

                    rightImg.setIcon(imgs[nowImage]);
                    try {
                        Thread.sleep(200);
                    } catch (Exception e) {
                        e.printStackTrace();
                    }    
                }
            }).start();
            
        }
    }//GEN-LAST:event_playActionPerformed

    private void rightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightActionPerformed
        // TODO add your handling code here:
        if(++nowImage > imgs.length-1){
            nowImage = 0;
        }
        
        leftImg.setIcon(imgs[nowImage]);
        if(nowImage < 10){
            load.setText("Load Image(duke0" + nowImage + ".gif)");
        }
        else if(nowImage >= 10){
            load.setText("Load Image(duke" + nowImage + ".gif)");
        }
        
    }//GEN-LAST:event_rightActionPerformed

    private void leftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftActionPerformed
        // TODO add your handling code here:
        if(--nowImage < 0){
            nowImage = imgs.length-1;
        }
        
        leftImg.setIcon(imgs[nowImage]);
        if(nowImage < 10){
            load.setText("Load Image(duke0" + nowImage + ".gif)");
        }
        else if(nowImage >= 10){
            load.setText("Load Image(duke" + nowImage + ".gif)");
        }
    }//GEN-LAST:event_leftActionPerformed

    private void stopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopActionPerformed
        // TODO add your handling code here:
        playControl = false;
    }//GEN-LAST:event_stopActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MI3A_26_02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MI3A_26_02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MI3A_26_02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MI3A_26_02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MI3A_26_02().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnArea;
    private javax.swing.JPanel imgArea;
    private javax.swing.JButton left;
    private javax.swing.JLabel leftImg;
    private javax.swing.JButton load;
    private javax.swing.JButton play;
    private javax.swing.JButton right;
    private javax.swing.JLabel rightImg;
    private javax.swing.JButton stop;
    // End of variables declaration//GEN-END:variables
}
