
import java.awt.Color;
import javax.swing.ButtonGroup;
import javax.swing.JRadioButton;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author steve
 */
public class Quiz_form extends javax.swing.JFrame {

    String[] questions = {"1 + 1 = ?", "3 + 3 = ?", "5 + 5 = ?", "10 x 9 = ?", "1 + 2 + 3 + ... + 10 = ?", };
    String[][] options = {{"10", "9", "2", "0", "2"}, {"15", "7", "6", "11", "6"}, {"20", "10", "50", "5", "10"}, {"80", "90", "70", "100", "90"}, {"60", "55", "45", "50", "55"}};
    //最後一個item是正確答案
    
    int index = 0, correct = 0;
    ButtonGroup bg = new ButtonGroup();

    // Creates new form Quiz_form

    public Quiz_form() {
            initComponents();

            bg.add(jRadioButton1_);
            bg.add(jRadioButton2_);
            bg.add(jRadioButton3_);
            bg.add(jRadioButton4_);

            Button_next_ActionPerformed(null);
    }
    
    public void getSelectedOption(JRadioButton rbtn){
            //1.get the selected value from the radiobutton
            //2.increment the index
            //3.disable other radiobutton

            // check if the user selected the true answer
            if(rbtn.getText().equals(options[index][4])){
                    correct++;
            }
            index++;
            enableRbutton(false);   
    }
    
    //enable/disable radiobuttons
    public void enableRbutton(boolean yes_or_no){
            jRadioButton1_.setEnabled(yes_or_no);
            jRadioButton2_.setEnabled(yes_or_no);
            jRadioButton3_.setEnabled(yes_or_no);
            jRadioButton4_.setEnabled(yes_or_no);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton4 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        Quiz_block = new javax.swing.JPanel();
        Quiz_label = new javax.swing.JLabel();
        jRadioButton1_ = new javax.swing.JRadioButton();
        jRadioButton2_ = new javax.swing.JRadioButton();
        jRadioButton3_ = new javax.swing.JRadioButton();
        jRadioButton4_ = new javax.swing.JRadioButton();
        Button_next_ = new javax.swing.JButton();

        jRadioButton4.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        Quiz_block.setBackground(new java.awt.Color(102, 102, 102));

        Quiz_label.setBackground(new java.awt.Color(153, 153, 153));
        Quiz_label.setFont(new java.awt.Font("新宋体", 1, 14)); // NOI18N
        Quiz_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Quiz_label.setText("jLabel1");

        javax.swing.GroupLayout Quiz_blockLayout = new javax.swing.GroupLayout(Quiz_block);
        Quiz_block.setLayout(Quiz_blockLayout);
        Quiz_blockLayout.setHorizontalGroup(
            Quiz_blockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Quiz_blockLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Quiz_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        Quiz_blockLayout.setVerticalGroup(
            Quiz_blockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Quiz_blockLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Quiz_label, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addContainerGap())
        );

        jRadioButton1_.setFont(new java.awt.Font("新宋体", 0, 12)); // NOI18N
        jRadioButton1_.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1_.setText("jRadioButton1");
        jRadioButton1_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1_ActionPerformed(evt);
            }
        });

        jRadioButton2_.setFont(new java.awt.Font("新宋体", 0, 12)); // NOI18N
        jRadioButton2_.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2_.setText("jRadioButton2");
        jRadioButton2_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2_ActionPerformed(evt);
            }
        });

        jRadioButton3_.setFont(new java.awt.Font("新宋体", 0, 12)); // NOI18N
        jRadioButton3_.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3_.setText("jRadioButton3");
        jRadioButton3_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3_ActionPerformed(evt);
            }
        });

        jRadioButton4_.setFont(new java.awt.Font("新宋体", 0, 12)); // NOI18N
        jRadioButton4_.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton4_.setText("jRadioButton4");
        jRadioButton4_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4_ActionPerformed(evt);
            }
        });

        Button_next_.setBackground(new java.awt.Color(255, 102, 51));
        Button_next_.setForeground(new java.awt.Color(255, 255, 255));
        Button_next_.setText("Next");
        Button_next_.setToolTipText("");
        Button_next_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_next_ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Button_next_, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Quiz_block, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton1_, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                    .addComponent(jRadioButton2_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton3_, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                    .addComponent(jRadioButton4_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Quiz_block, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jRadioButton1_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton2_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton3_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton4_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(44, 44, 44)
                .addComponent(Button_next_, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_next_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_next_ActionPerformed
        
        // Restart the Quiz
        if(Button_next_.getText().equals("Restart The Quiz")){
                Button_next_.setText("Next");
                Quiz_block.setBackground(new java.awt.Color(102, 102, 102));
                index = 0;
                correct = 0;
        }

        if(index == questions.length){
                // show the result of quiz
                Quiz_label.setText("Your Score: " + correct + " / " + questions.length);
                if(correct >= (float)questions.length / 2){
                        Quiz_block.setBackground(Color.GREEN);
                }
                else{
                        Quiz_block.setBackground(Color.RED);
                }
                Button_next_.setText("Restart The Quiz");
        }      
        else{
                // Enable radiobuttons
                enableRbutton(true);

                // Display next question
                Quiz_label.setText(questions[index]);
                jRadioButton1_.setText(options[index][0]);
                jRadioButton2_.setText(options[index][1]);
                jRadioButton3_.setText(options[index][2]);
                jRadioButton4_.setText(options[index][3]);

                if(index == questions.length-1){
                        Button_next_.setText("Finish and See The Result");
                }           
        }
        // Clear the selects
        bg.clearSelection();
    }//GEN-LAST:event_Button_next_ActionPerformed
    
    private void jRadioButton3_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3_ActionPerformed
//         index++;
            getSelectedOption(jRadioButton3_);
    }//GEN-LAST:event_jRadioButton3_ActionPerformed

    private void jRadioButton4_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4_ActionPerformed
//         index++;
            getSelectedOption(jRadioButton4_);
    }//GEN-LAST:event_jRadioButton4_ActionPerformed

    private void jRadioButton1_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1_ActionPerformed
//         increment to the next question.
//         index++;
            getSelectedOption(jRadioButton1_);
    }//GEN-LAST:event_jRadioButton1_ActionPerformed

    private void jRadioButton2_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2_ActionPerformed
//         index++;
            getSelectedOption(jRadioButton2_);
    }//GEN-LAST:event_jRadioButton2_ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quiz_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quiz_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quiz_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quiz_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Quiz_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_next_;
    private javax.swing.JPanel Quiz_block;
    private javax.swing.JLabel Quiz_label;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1_;
    private javax.swing.JRadioButton jRadioButton2_;
    private javax.swing.JRadioButton jRadioButton3_;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton4_;
    // End of variables declaration//GEN-END:variables
}
