                                                                                                                  /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package HWK8;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author jschang
 */
public class MI3A_26_HWK8_03 extends javax.swing.JFrame {

    /**
     * Creates new form P206_SplitPaneFrame
     */
    File getFile = new File("");
    
    public MI3A_26_HWK8_03() {
        initComponents();
        setLocationRelativeTo(null);  //置中顯示
        this.setSize(500, 500);
        this.setTitle("竄改歷史的盜墓賊啊......你將付出代價......");
    }

    void showFileContent(String path) throws FileNotFoundException, IOException{
        try(BufferedReader br = new BufferedReader(new FileReader(path))){
            String line, content = "";
            while((line=br.readLine()) != null){
                content += line+"\n";
            }
            fileText.setText(content);
        }
    }
    
    void writeBackToFile() throws IOException{
        JFrame Block = new JFrame();
        
        try(BufferedWriter bw = new BufferedWriter(new FileWriter(filePath.getText()))){
            bw.write(fileText.getText());
            JOptionPane.showMessageDialog(Block, "在這份文件，你留下了一道新的傷痕......");
        }
    }
    
    void buildFile(String path) throws IOException{
        File newFile = new File(path);
        newFile.createNewFile();
        JFrame Block = new JFrame();
        
        try(BufferedWriter bw = new BufferedWriter(new FileWriter(path))){
            bw.write(fileText.getText());
            JOptionPane.showMessageDialog(Block, "新的歷史誕生了......");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchFile = new javax.swing.JFileChooser();
        saveFile = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        open = new javax.swing.JButton();
        save = new javax.swing.JButton();
        saveAs = new javax.swing.JButton();
        filePath = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        fileText = new javax.swing.JTextArea();

        searchFile.setDialogType(javax.swing.JFileChooser.CUSTOM_DIALOG);
        searchFile.setApproveButtonText("");
        searchFile.setCurrentDirectory(new java.io.File("D:\\Data\\HWK8"));
        searchFile.setDialogTitle("開啟檔案");

        saveFile.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        saveFile.setDialogTitle("尋找目的地");
        saveFile.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        open.setFont(new java.awt.Font("精品點陣體7×7", 0, 18)); // NOI18N
        open.setText("OPEN");
        open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openActionPerformed(evt);
            }
        });

        save.setFont(new java.awt.Font("精品點陣體7×7", 0, 18)); // NOI18N
        save.setText("SAVE");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        saveAs.setFont(new java.awt.Font("精品點陣體7×7", 0, 18)); // NOI18N
        saveAs.setText("SAVE AS...");
        saveAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAsActionPerformed(evt);
            }
        });

        filePath.setFont(new java.awt.Font("Stick", 0, 18)); // NOI18N
        filePath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filePathActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(open)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveAs)
                        .addGap(0, 209, Short.MAX_VALUE))
                    .addComponent(filePath))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(saveAs, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(open, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(save, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(filePath, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        fileText.setColumns(20);
        fileText.setFont(new java.awt.Font("源樣明體 M", 0, 14)); // NOI18N
        fileText.setRows(5);
        jScrollPane1.setViewportView(fileText);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openActionPerformed
        // TODO add your handling code here:
        int code = searchFile.showOpenDialog(null);
        if(code == JFileChooser.APPROVE_OPTION){
            getFile = searchFile.getSelectedFile();
            System.out.println("Get File: " + getFile.getPath());
            
            filePath.setText(getFile.getPath());
            try {
                showFileContent(getFile.getPath());
            } catch (IOException ex) {
                Logger.getLogger(MI3A_26_HWK8_03.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_openActionPerformed

    private void filePathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filePathActionPerformed
        // TODO add your handling code here:
//        if(filePath.getText().equals("為什麼要用這種奇怪的語調？"))
//            fileText.setText("因為感覺比較有FU啦哈哈 o(*￣▽￣*)ブ");
//        else{
            try{
                showFileContent(filePath.getText());
            }catch(Exception e){
                fileText.setText("Not found. Maybe you get an error file.");
            }
//        }
    }//GEN-LAST:event_filePathActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        JFrame warning = new JFrame();
        try {
            // TODO add your handling code here:
            writeBackToFile();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(warning, "【儲存失敗】\n好像哪裡怪怪的......路徑嗎？", "AAAAAA",JOptionPane.WARNING_MESSAGE);
            Logger.getLogger(MI3A_26_HWK8_03.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_saveActionPerformed

    private void saveAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAsActionPerformed
        // TODO add your handling code here:
        JFrame confirm = new JFrame();
        JOptionPane.showMessageDialog(confirm, "即將另存新檔，請確認輸入欄的路徑與現檔案相同。\n(點擊檔案時，下方會同步顯示路徑。\n請將路徑清空後輸入新檔案的名稱。)");
        
        int code = saveFile.showSaveDialog(null);
        if(code == JFileChooser.APPROVE_OPTION){
            getFile = saveFile.getSelectedFile();
            
            String fileExtension = filePath.getText().substring(filePath.getText().lastIndexOf("."), filePath.getText().length());
            System.out.println("choose File: " + getFile.getPath()+fileExtension);

            try {
                buildFile(getFile.getPath()+fileExtension);
            } catch (IOException ex) {
                Logger.getLogger(MI3A_26_HWK8_03.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_saveAsActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MI3A_26_HWK8_03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MI3A_26_HWK8_03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MI3A_26_HWK8_03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MI3A_26_HWK8_03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MI3A_26_HWK8_03().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField filePath;
    private javax.swing.JTextArea fileText;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton open;
    private javax.swing.JButton save;
    private javax.swing.JButton saveAs;
    private javax.swing.JFileChooser saveFile;
    private javax.swing.JFileChooser searchFile;
    // End of variables declaration//GEN-END:variables
}
