/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package HWK8;

import java.awt.Color;
import java.awt.Container;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Random;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author jschang
 */
public class MI3A_26_HWK8_02 extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form P202_FlowLayoutFrame
     */

    JButton[] jb = new JButton[9];
    Random r = new Random();
    int move = 0;
    int blue = 0;
    
    public MI3A_26_HWK8_02() {
        initComponents();
        setLocationRelativeTo(null);  //置中顯示
        this.setSize(420, 420);
        this.setTitle("這雖然是遊戲，但可不是鬧著玩的。");
       
        Container cp = this.getContentPane();
        cp.setLayout(new GridBagLayout());
        GridBagConstraints gbc=new GridBagConstraints();
        gbc.fill=GridBagConstraints.BOTH;
        
        beautyTitle();
        setGrid(gbc, 0,0,1,1,1,1);
        cp.add(p1,gbc);
        
        fullArray(jb);
        swapAndShow(jb, cp, gbc, p2);
    }
    
    void beautyTitle(){
        title.setHorizontalAlignment(JLabel.CENTER);
        title.setVerticalAlignment(JLabel.CENTER);
        p1.add(title);
    }
    void fullArray(JButton[] jb){
        for(int i = 0; i < jb.length; i++){
            jb[i] = new JButton(""+(i+1));
            jb[i].setFont(new Font("Klee One", Font.BOLD, 21));
            jb[i].setBackground(new Color(51,204,255));
        }
    }
    void swapAndShow(JButton[] jb, Container cp, GridBagConstraints gbc, JPanel p2){
        JButton temp;
        for(int i = 0; i < jb.length; i++){
            int s = i+r.nextInt(9-i);
            temp = jb[i];
            jb[i] = jb[s];
            jb[s] = temp;
            
            p2.add(jb[i]);
            jb[i].addActionListener(this);
        }
        
        setButtonName();
        setGrid(gbc, 0,1,1,1,1,3);
        cp.add(p2, gbc);
    }
    void setGrid(GridBagConstraints gbc, int gridx, int gridy, int gridwidth, int gridheight, int weightx, int weighty){
        gbc.gridx=gridx;            // 起始座標
        gbc.gridy=gridy;
        gbc.gridwidth=gridwidth;    // 占用格數
        gbc.gridheight=gridheight;
        gbc.weightx=weightx;      // 縮放權重(0:在縮放時完全不變)
        gbc.weighty=weighty;
    }
    void setButtonName(){
        for(int i = 0; i < jb.length; i++){
            jb[i].setName(""+(i+1));
        }
    }
    
    @Override
    public void actionPerformed(ActionEvent e){
        for(int i = 0; i < jb.length; i++){
            if(e.getSource() == jb[i]){                 // 按下按鈕後，逐一檢視是哪個按鈕被點到
                String temp;
                temp = jb[i].getText();
                jb[i].setText(jb[4].getText());
                jb[4].setText(temp);
                
                title.setText("Move: " + (++move));
                title.setForeground(new Color(r.nextInt(128), r.nextInt(128), r.nextInt(128)));
                
                finishBlock(checkFinish());
            }
        }
    }
    
    boolean checkFinish(){
        for(JButton j : jb){
            if(!(j.getName().equals(j.getText())))
                return false;
        }
        return true;
    }
    void finishBlock(boolean check){
        if(check){
            JFrame block = new JFrame();
            JOptionPane.showMessageDialog(block, "你完成了拼圖！[]~(￣▽￣)~*", "恭喜", JOptionPane.PLAIN_MESSAGE);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        p2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(360, 420));

        p1.setLayout(new java.awt.BorderLayout());

        title.setFont(new java.awt.Font("Klee One SemiBold", 1, 36)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Move: 0");
        p1.add(title, java.awt.BorderLayout.CENTER);

        p2.setPreferredSize(new java.awt.Dimension(360, 360));
        p2.setVerifyInputWhenFocusTarget(false);
        p2.setLayout(new java.awt.GridLayout(3, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(p1, 67, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MI3A_26_HWK8_02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MI3A_26_HWK8_02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MI3A_26_HWK8_02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MI3A_26_HWK8_02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MI3A_26_HWK8_02().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel p1;
    private javax.swing.JPanel p2;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
